env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.49.zip
sudo: false
cache: bundler

jobs:
  include:
    - stage: python
      name: "Python tests"
      language: python
      python: "3.7"
      before_script:
        - pip install -r requirements.txt
      script: util/buildsite.py -r -f RDFExport.nquads

    - stage: ruby
      name: "Ruby Linter"
      language: python
      python: "3.7"
      language: ruby
      rvm: 2.6
      env: SOFT_LINT=true
      before_install:
        - 'gem update --system --conservative || (gem i "rubygems-update:~>2.7" --no-document && update_rubygems)'
        - 'gem update bundler --conservative'
        - bundle install --gemfile=scripts/Gemfile
      before_script:
        - pip install -r requirements.txt
        - util/buildsite.py -f RDFExport.nquads
        - cp -r site/releases/`util/schemaversion.py` site/releases/LATEST
      script: (cd scripts; bundle exec rake)
