language: python

python:
  - "2.7"

before_script:
  - SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.49.zip
  - wget $SDK_URL -nv -O google_appengine.zip
  - unzip -q google_appengine.zip
  - rm google_appengine.zip
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/google_appengine/
  - rvm install 2.4.0
script:
  - python scripts/run_tests.py
  - bundle exec rake
sudo: false