env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.49.zip
sudo: false
cache: bundler

jobs:
  include:
    - stage: python
      name: "Python tests"
      language: python
      python: "2.7"
      before_script:
        - wget $SDK_URL -nv -O google_appengine.zip
        - unzip -q google_appengine.zip
        - rm google_appengine.zip
        - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/google_appengine/
        - scripts/buildreleasefiles.sh -y -e -l "nquads nt" LATEST
      script: python scripts/run_tests.py

    - stage: ruby
      name: "Ruby Linter"
      language: ruby
      rvm: 2.6
      env: SOFT_LINT=true
      before_install:
        - bundle install --gemfile=scripts/Gemfile
      before_script:
        - wget $SDK_URL -nv -O google_appengine.zip
        - unzip -q google_appengine.zip
        - rm google_appengine.zip
        - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/google_appengine/
        - scripts/buildreleasefiles.sh -y -e -l "nquads nt" LATEST
      script: (cd scripts; bundle exec rake)
