env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler

jobs:
  include:
    - stage: python
      name: "Python tests"
      language: python
      python: "3.7"
      before_script:
        - pip install -r requirements.txt
      script: util/buildsite.py -r

    - stage: ruby
      name: "Ruby Linter"
      language: ruby
      rvm: 2.6
      env: SOFT_LINT=true
      before_install:
        - 'gem update --system --conservative || (gem i "rubygems-update:~>2.7" --no-document && update_rubygems)'
        - 'gem update bundler --conservative'
        - bundle install --gemfile=scripts/Gemfile
      before_script:
        - source ~/virtualenv/python3.7/bin/activate
        - pip install -r requirements.txt
        - util/buildsite.py -f Context RDFExport.nquads 
        - deactivate
        - mkdir site/releases/LATEST
        - ls -l site/releases
        - (cd site/releases/`util/schemaversion.py`;pwd;ls -l ..; cp -r * ../LATEST)
      script: (cd scripts; bundle exec rake)
