language: python

python:
  - "2.7"
env: SOFT_LINT=true
before_script:
  - SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.49.zip
  - wget $SDK_URL -nv -O google_appengine.zip
  - unzip -q google_appengine.zip
  - rm google_appengine.zip
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/google_appengine/
  - rvm install 2.4.0
  - bundle install --gemfile=scripts/Gemfile
  - wget https://github.com/validator/validator/releases/download/17.9.0/vnu.jar_17.9.0.zip
  - unzip -q vnu.jar_17.9.0.zip
script:
  - python scripts/run_tests.py
  - (cd scripts; bundle exec rake)
  - java -jar dist/vnu.jar data/schema.rdfa
sudo: false
